name: clustering      # any name for the environment
channels:
- conda-forge
dependencies:         # everything under this, installed by conda
- python

- numpy
- matplotlib
- pandas
- scikit-learn==0.22.1 # not higher, otherwise troubles with coclust package
- scikit-bio
- pip:                # everything under this, installed by pip
  - Coclust
  - pyclustertend
  - multiview
